window.CLUB_DATA = {
    "last_updated": "09.07.2026 14:46:23",
    "clubs": [
        {
            "venue": "VH Underground Fools e.V.",
            "street": "Weiherstrasse 30",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Rene Irion",
            "mobile": "0177 9109890",
            "website": "",
            "contact_email": "reneirion1401@gmail.com",
            "email": "",
            "name": "DC Oststadt",
            "number": "002",
            "url": "https://www.bwedl.de/vereine/dc-oststadt/"
        },
        {
            "venue": "Schützenhaus SV Eisingen e.V.",
            "street": "Weberstraße 60",
            "city": "Eisingen",
            "phone": "07231 4194128",
            "fax": "",
            "contact": "Karin Maischhofer",
            "mobile": "0176 81033626",
            "website": "",
            "contact_email": "dc_strikers@online.de",
            "email": "dc_strikers@online.de",
            "name": "DC Striker´s",
            "number": "003",
            "url": "https://www.bwedl.de/vereine/dc-strikers/"
        },
        {
            "venue": "VH DC Underground Fool's e.V.",
            "street": "Weiherstraße 30",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Timo Gröschl",
            "mobile": "01573 6810226",
            "website": "",
            "contact_email": "timogroschl@gmail.com",
            "email": "timogroschl@gmail.com",
            "name": "DC Underground Fool´s e.V.",
            "number": "004",
            "url": "https://www.bwedl.de/vereine/dc-underground-fools-e.v/"
        },
        {
            "venue": "Bistro Colours",
            "street": "Königsbacherstr. 6",
            "city": "Königsbach - Stein",
            "phone": "07232 4471",
            "fax": "",
            "contact": "Michael Horntrich",
            "mobile": "01522 7161312",
            "website": "",
            "contact_email": "michael.horntrich@dc-180-stein.de",
            "email": "info@bistro-colours.de",
            "name": "DC 180 Stein e.V.",
            "number": "005",
            "url": "https://www.bwedl.de/vereine/dc-180-stein-e.v/"
        },
        {
            "venue": "VdH Knittlingen e.V.",
            "street": "Freudensteinerstrasse 92",
            "city": "Knittlingen",
            "phone": "",
            "fax": "",
            "contact": "Alfred Eigl",
            "mobile": "0151 54400674",
            "website": "",
            "contact_email": "a.eigl@yahoo.com",
            "email": "a.eigl@yahoo.com",
            "name": "DC Mephistos",
            "number": "009",
            "url": "https://www.bwedl.de/vereine/dc-mephistos/"
        },
        {
            "venue": "Tasos Bistro",
            "street": "Rathausplatz 1",
            "city": "Mühlacker-Enzberg",
            "phone": "07041 860617",
            "fax": "",
            "contact": "Anastasios Spyropoulos",
            "mobile": "0170 3527361",
            "website": "",
            "contact_email": "",
            "email": "spyropoulos@aol.com",
            "name": "TDF Enzberg",
            "number": "010",
            "url": "https://www.bwedl.de/vereine/tdf-enzberg/"
        },
        {
            "venue": "The Dubliner Irish Pub",
            "street": "Hauptstr. 105",
            "city": "Straubenhardt",
            "phone": "",
            "fax": "",
            "contact": "Dirk Schuhmacher",
            "mobile": "0177 3880144",
            "website": "http://www.thedubliner.pub",
            "contact_email": "dirk.schuhmacher@gmx.net",
            "email": "dirk.schuhmacher@gmx.net",
            "name": "DC Shamrock",
            "number": "012",
            "url": "https://www.bwedl.de/vereine/dc-shamrock/"
        },
        {
            "venue": "Tequila-Bar",
            "street": "Marktplatz 2",
            "city": "Birkenfeld",
            "phone": "0155 67043113",
            "fax": "",
            "contact": "Denis Orta",
            "mobile": "0152 33803522",
            "website": "",
            "contact_email": "denis.orta@yahoo.de",
            "email": "ginodelviscio@gmail.com",
            "name": "DC HighFlights",
            "number": "013",
            "url": "https://www.bwedl.de/vereine/dc-highflights/"
        },
        {
            "venue": "Blumenheckstüble",
            "street": "Hohenstaufenstr. 42",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Maik Hölzle",
            "mobile": "0173 3054319",
            "website": "",
            "contact_email": "maik196@gmx.net",
            "email": "maik196@gmx.net",
            "name": "DC Texas Team",
            "number": "015",
            "url": "https://www.bwedl.de/vereine/dc-texas-team/"
        },
        {
            "venue": "X Cafe Bistro",
            "street": "Westliche-Karl-Friedrich- Str. 259",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Tanja Eßwein",
            "mobile": "0176 30423942",
            "website": "",
            "contact_email": "tanyaesswein@gmail.com",
            "email": "sauerleo80@gmail.com",
            "name": "the Enz Coast",
            "number": "016",
            "url": "https://www.bwedl.de/vereine/the-enz-coast/"
        },
        {
            "venue": "Hörgeschädigten Zentrum",
            "street": "Hohenstauffenstr. 15",
            "city": "Pforzheim",
            "phone": "0176 54586139",
            "fax": "",
            "contact": "Markus Bethke",
            "mobile": "WhatsApp 0176 24844987",
            "website": "http://www.gsvpforzheim.de",
            "contact_email": "vorstand@gsvpforzheim.de",
            "email": "vorstand@gsvpforzheim.de",
            "name": "DC Kolibrispitz",
            "number": "017",
            "url": "https://www.bwedl.de/vereine/dc-kolibrispitz/"
        },
        {
            "venue": "Brötzingerstüble",
            "street": "Westliche-Karl-Friedrich-Str.378",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Jessica Koch",
            "mobile": "0176 23382422",
            "website": "",
            "contact_email": "dcknickebocker@gmail.com",
            "email": "",
            "name": "DC Knickebocker",
            "number": "018",
            "url": "https://www.bwedl.de/vereine/dc-knickebocker/"
        },
        {
            "venue": "Sports Bar Karlsbad",
            "street": "Hauptstraße 40",
            "city": "Karlsbad",
            "phone": "",
            "fax": "",
            "contact": "Edgar Käser",
            "mobile": "0176 21159984",
            "website": "",
            "contact_email": "edgarkaeser@web.de",
            "email": "",
            "name": "DC Triple X",
            "number": "020",
            "url": "https://www.bwedl.de/vereine/dc-triple-x/"
        },
        {
            "venue": "Why Not",
            "street": "Spitalstr. 7",
            "city": "Vaihingen Enz",
            "phone": "0151 61400132",
            "fax": "",
            "contact": "Asterios Karelas",
            "mobile": "0151 61400132",
            "website": "http://www.whynot-bei-fani.de",
            "contact_email": "fanis@gmx.net",
            "email": "fanis@gmx.net",
            "name": "DC Duselbrüder",
            "number": "023",
            "url": "https://www.bwedl.de/vereine/dc-duselbruder/"
        },
        {
            "venue": "Jugendraum Großglattbach",
            "street": "Ritterweg 25",
            "city": "Mühlacker",
            "phone": "",
            "fax": "",
            "contact": "Janette Weingärtner",
            "mobile": "01520 9173386",
            "website": "http://www.jugendraumev.de",
            "contact_email": "janette.weingaertner@outlook.com",
            "email": "Vorstandschaft@jugendraumev.de",
            "name": "DSV Großglabbich",
            "number": "024",
            "url": "https://www.bwedl.de/vereine/dsv-grossglabbich/"
        },
        {
            "venue": "Gaststätte Meyerhöfle",
            "street": "Bertholdstr. 28",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Alexander Schmidt",
            "mobile": "0176 31492625",
            "website": "",
            "contact_email": "wichtel3@hotmail.com",
            "email": "wichtel3@hotmail.com",
            "name": "Alla Häeeeehr",
            "number": "025",
            "url": "https://www.bwedl.de/vereine/alla-haeeeehr/"
        },
        {
            "venue": "Bistro U-Boot",
            "street": "Langwiesenweg 51",
            "city": "Bad Wildbad",
            "phone": "",
            "fax": "",
            "contact": "Lee Scott Galletly",
            "mobile": "0160 7254002",
            "website": "",
            "contact_email": "leeascottgalletly@googlemail.com",
            "email": "leeascottgalletly@googlemail.com",
            "name": "DC Broken Darts",
            "number": "026",
            "url": "https://www.bwedl.de/vereine/dc-broken-darts/"
        },
        {
            "venue": "Schützenhaus SV Eisingen e.V.",
            "street": "Weberstr. 60",
            "city": "Eisingen",
            "phone": "",
            "fax": "",
            "contact": "Mike Bader",
            "mobile": "0171 3357771",
            "website": "",
            "contact_email": "mike_bader5@hotmail.com",
            "email": "a.rados88@aol.com",
            "name": "DC Green Scorpion's",
            "number": "027",
            "url": "https://www.bwedl.de/vereine/dc-green-scorpions/"
        },
        {
            "venue": "Reiterstüble Eppingen",
            "street": "Talstraße 25",
            "city": "Eppingen",
            "phone": "",
            "fax": "",
            "contact": "Daniel Hautzinger",
            "mobile": "0177 5898906",
            "website": "http://www.reiterstueble-eppingen.de",
            "contact_email": "danielhautzinger9@gmail.com",
            "email": "reiterstueble.eppingen@gmail.com",
            "name": "DC Reloaded",
            "number": "029",
            "url": "https://www.bwedl.de/vereine/dc-reloaded/"
        },
        {
            "venue": "Maddox-Club-Bar",
            "street": "Stuttgarter Str. 1",
            "city": "Knittlingen",
            "phone": "",
            "fax": "",
            "contact": "Charalambos Papadopoulos",
            "mobile": "0172 6384407",
            "website": "",
            "contact_email": "ch.papadopoulos@gmx.de",
            "email": "ch.papadopoulos@gmx.de",
            "name": "DC Black Scorpions",
            "number": "030",
            "url": "https://www.bwedl.de/vereine/dc-black-scorpions/"
        },
        {
            "venue": "Y Cafe-Bistro",
            "street": "Am Waisenhausplatz 18",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Ilhami Kücük",
            "mobile": "0173 9804645",
            "website": "",
            "contact_email": "ilhami64@web.de",
            "email": "ilhami64@web.de",
            "name": "DC Cim Bom",
            "number": "031",
            "url": "https://www.bwedl.de/vereine/dc-cim-bom/"
        },
        {
            "venue": "Reiterstüble",
            "street": "Talstraße 25",
            "city": "Eppingen",
            "phone": "",
            "fax": "",
            "contact": "Vanessa Lenz",
            "mobile": "0176 47686865",
            "website": "",
            "contact_email": "lenzvanessa@t-online.de",
            "email": "info@reiterstueble-eppingen.de",
            "name": "Friends Arrows",
            "number": "032",
            "url": "https://www.bwedl.de/vereine/friends-arrows/"
        },
        {
            "venue": "Bistro Dallas",
            "street": "Am Waisenhausplatz 26",
            "city": "Pforzheim",
            "phone": "07231 351620",
            "fax": "",
            "contact": "Maria Dangulea",
            "mobile": "0151 11012313",
            "website": "",
            "contact_email": "mariadangulea84@yahoo.com",
            "email": "",
            "name": "DC Drei Daneben",
            "number": "033",
            "url": "https://www.bwedl.de/vereine/dc-drei-daneben/"
        },
        {
            "venue": "VH DC Crazy Flights (VFL Höfen)",
            "street": "Simonswiesen 2",
            "city": "Höfen",
            "phone": "",
            "fax": "",
            "contact": "Christian Marienfeld",
            "mobile": "0157 50125348",
            "website": "",
            "contact_email": "cmarienfeld9@gmail.com",
            "email": "",
            "name": "DC Crazy Flights",
            "number": "037",
            "url": "https://www.bwedl.de/vereine/dc-crazy-flights/"
        },
        {
            "venue": "Scharfes Eck",
            "street": "Hugo-Römpler-Straße 31",
            "city": "Schömberg",
            "phone": "",
            "fax": "",
            "contact": "Tobias Kling",
            "mobile": "0173 1738296",
            "website": "",
            "contact_email": "",
            "email": "erichmesser5@gmail.com",
            "name": "DC SchömbergerEck",
            "number": "038",
            "url": "https://www.bwedl.de/vereine/dc-schombergereck/"
        },
        {
            "venue": "Schützenhaus SV Eisingen e.V.",
            "street": "Weberstr. 60",
            "city": "Eisingen",
            "phone": "",
            "fax": "",
            "contact": "Michael Thiel",
            "mobile": "0172 7423478",
            "website": "",
            "contact_email": "michaelthiel07@gmail.com",
            "email": "michaelthiel07@gmail.com",
            "name": "DC Destroyers e.V.",
            "number": "039",
            "url": "https://www.bwedl.de/vereine/dc-destroyers-e.v/"
        },
        {
            "venue": "Eurobar Eventhaus",
            "street": "Pflügerstraße 37",
            "city": "Pforzheim",
            "phone": "0176 80230147",
            "fax": "",
            "contact": "Marco Merz",
            "mobile": "0176 80230147",
            "website": "",
            "contact_email": "marco_merz@hotmail.de",
            "email": "eurobarpforzheim@outlook.de",
            "name": "the Metal Darts",
            "number": "040",
            "url": "https://www.bwedl.de/vereine/the-metal-darts/"
        },
        {
            "venue": "SpVgg Conweiler-Schwann e.V.",
            "street": "Am Sportplatz",
            "city": "Straubenhardt",
            "phone": "07082 940485",
            "fax": "",
            "contact": "Michael Kiefer",
            "mobile": "0160 97337211",
            "website": "https://coschwa.de",
            "contact_email": "m.kiefer@t-online.de",
            "email": "m.kiefer@t-online.de",
            "name": "DC Conweiler",
            "number": "041",
            "url": "https://www.bwedl.de/vereine/dc-conweiler/"
        },
        {
            "venue": "Wunderbar",
            "street": "Kirchstr. 41",
            "city": "Remchingen",
            "phone": "",
            "fax": "",
            "contact": "Danielle Aymar",
            "mobile": "0163 2029063",
            "website": "",
            "contact_email": "danielleaymar@yahoo.de",
            "email": "",
            "name": "DC Bull Hunters",
            "number": "042",
            "url": "https://www.bwedl.de/vereine/dc-bull-hunters/"
        },
        {
            "venue": "Schützenhaus Königsbach",
            "street": "Allmendäckerle 1",
            "city": "Königsbach",
            "phone": "",
            "fax": "",
            "contact": "Jannik Scherle",
            "mobile": "0176 72756980",
            "website": "",
            "contact_email": "jannik.scherle@web.de",
            "email": "",
            "name": "DC Irish 26 e.V.",
            "number": "043",
            "url": "https://www.bwedl.de/vereine/dc-irish-26-e.v/"
        },
        {
            "venue": "Hotel Ochsen",
            "street": "Schwarzwaldstr. 7",
            "city": "Neuenbürg - Arnbach",
            "phone": "07082 4131607",
            "fax": "",
            "contact": "Sascha Miegel",
            "mobile": "0157 73550826",
            "website": "",
            "contact_email": "sascha.miegel@gmx.net",
            "email": "",
            "name": "DC Bull's Eye Arnbach",
            "number": "044",
            "url": "https://www.bwedl.de/vereine/dc-bulls-eye-arnbach/"
        },
        {
            "venue": "Blumenheckstüble",
            "street": "Hohenstaufenstr. 42",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Franke Polte",
            "mobile": "0172 6250626",
            "website": "",
            "contact_email": "",
            "email": "dartfreunde.eichenherz@web.de",
            "name": "Dartfreunde Eichenherz",
            "number": "049",
            "url": "https://www.bwedl.de/vereine/dartfreunde-eichenherz/"
        },
        {
            "venue": "Bistro U-Boot",
            "street": "Langwiesenweg 51",
            "city": "Bad Wildbad",
            "phone": "07081 9560054",
            "fax": "",
            "contact": "Fabian Steube",
            "mobile": "0160 7632518",
            "website": "http://www.hofer-automaten.de",
            "contact_email": "f.steube@t-online.de",
            "email": "info@hofer-automaten.de",
            "name": "DC Lachs 14",
            "number": "052",
            "url": "https://www.bwedl.de/vereine/dc-lachs-14/"
        },
        {
            "venue": "Kost & Bar",
            "street": "Hauptstraße 95",
            "city": "Remchingen/Wilferdingen",
            "phone": "",
            "fax": "",
            "contact": "Thorsten Klein",
            "mobile": "0162 6977070",
            "website": "",
            "contact_email": "thorstenklein358@gmail.com",
            "email": "",
            "name": "Odins Knechte",
            "number": "053",
            "url": "https://www.bwedl.de/vereine/odins-knechte/"
        },
        {
            "venue": "Eurobar Eventhaus",
            "street": "Pflügerstraße 37",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Bojan Sabo",
            "mobile": "0162 5600589",
            "website": "",
            "contact_email": "bojansabo@web.de",
            "email": "eurobarpforzheim@outlook.de",
            "name": "DC Lightning Arrows",
            "number": "054",
            "url": "https://www.bwedl.de/vereine/dc-lightning-arrows/"
        },
        {
            "venue": "Bar U-Boot",
            "street": "Langwiesenweg 51",
            "city": "Bad Wildbad",
            "phone": "",
            "fax": "",
            "contact": "Tobias Reikowski",
            "mobile": "0173 9078239",
            "website": "",
            "contact_email": "008runner@gmail.com",
            "email": "info@hofer-automaten.de",
            "name": "DC Enztaler Buben",
            "number": "055",
            "url": "https://www.bwedl.de/vereine/dc-enztaler-buben/"
        },
        {
            "venue": "X Cafe Bistro",
            "street": "Westliche-Karl-Friedrich-Str. 259",
            "city": "Pforzheim",
            "phone": "0157 30854547",
            "fax": "",
            "contact": "Felix Bock",
            "mobile": "0173 8903752",
            "website": "",
            "contact_email": "felixbock@gmx.de",
            "email": "beti.luca@yahoo.de",
            "name": "DC X-Brötzingen",
            "number": "056",
            "url": "https://www.bwedl.de/vereine/dc-x-brotzingen/"
        },
        {
            "venue": "Sportheim Mile",
            "street": "Pforzheimer Straße 60",
            "city": "Schömberg/Schwarzenberg",
            "phone": "07084 7492",
            "fax": "",
            "contact": "Artur Penner",
            "mobile": "0176 32552217",
            "website": "",
            "contact_email": "artur.penner@hotmail.com",
            "email": "",
            "name": "DC Ungültig",
            "number": "057",
            "url": "https://www.bwedl.de/vereine/dc-ungultig/"
        },
        {
            "venue": "Gaststätte Meyerhöfle",
            "street": "Bertholdstr. 28",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Mareike Zahnlecker",
            "mobile": "01590 1363776",
            "website": "",
            "contact_email": "mareike.zahnlecker@web.de",
            "email": "",
            "name": "the flying Rocks",
            "number": "058",
            "url": "https://www.bwedl.de/vereine/the-flying-rocks/"
        },
        {
            "venue": "Euribar Eventhaus",
            "street": "Pflügerstraße 37",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Marc Grünwaldt",
            "mobile": "0176 31761531",
            "website": "",
            "contact_email": "",
            "email": "Mgruenwaldt@gmail.com",
            "name": "Phantom Arrows",
            "number": "059",
            "url": "https://www.bwedl.de/vereine/phantom-arrows/"
        },
        {
            "venue": "Cafe Nero",
            "street": "Hauptstraße 12",
            "city": "Weissach",
            "phone": "0151 15789880",
            "fax": "",
            "contact": "Thomas Bauer",
            "mobile": "0172 7328010",
            "website": "",
            "contact_email": "urmelbauer@web.de",
            "email": "",
            "name": "DC Crows",
            "number": "060",
            "url": "https://www.bwedl.de/vereine/dc-crows/"
        },
        {
            "venue": "Bistro Orchidee",
            "street": "Liebenzellerstr. 35",
            "city": "Schömberg",
            "phone": "",
            "fax": "",
            "contact": "Kevin Schleeh",
            "mobile": "0176 87330948",
            "website": "",
            "contact_email": "kevinschleeh@gmx.de",
            "email": "",
            "name": "DC Oiloch Schömberg",
            "number": "061",
            "url": "https://www.bwedl.de/vereine/dc-oiloch-schomberg/"
        },
        {
            "venue": "Bistro Dallas",
            "street": "Am Waisenhausplatz 26",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Hans-Peter Kalweit",
            "mobile": "0176 47377300",
            "website": "",
            "contact_email": "hanspeterk447@googlemail.com",
            "email": "",
            "name": "DC Triple 7",
            "number": "062",
            "url": "https://www.bwedl.de/vereine/dc-triple-7/"
        },
        {
            "venue": "The Dubliner Irish Pub",
            "street": "Hauptstr. 105",
            "city": "Straubenhardt-Schwann",
            "phone": "",
            "fax": "",
            "contact": "Marco Krell",
            "mobile": "01578 2333232",
            "website": "https://thedubliner.pub",
            "contact_email": "dc@dart-vaders.de",
            "email": "hallo@thedubliner.pub",
            "name": "DC Dart Vaders",
            "number": "064",
            "url": "https://www.bwedl.de/vereine/dc-dart-vaders/"
        },
        {
            "venue": "Baradox",
            "street": "Durlacherstraße 63",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Ulrike Veit",
            "mobile": "0172 7182489",
            "website": "",
            "contact_email": "therock69@gmx.de",
            "email": "therock69@gmx.de",
            "name": "Los Muertos",
            "number": "065",
            "url": "https://www.bwedl.de/vereine/los-muertos/"
        },
        {
            "venue": "Paselino Sportsbar",
            "street": "Daimlerstraße 2",
            "city": "Wiernsheim",
            "phone": "07044 4929779",
            "fax": "",
            "contact": "Oliver Gille",
            "mobile": "0151 58554253",
            "website": "http://www.paselino.de",
            "contact_email": "muehle.glabbich@web.de",
            "email": "",
            "name": "Glabbicher Bulls",
            "number": "066",
            "url": "https://www.bwedl.de/vereine/muhle-glabbich-e.v/"
        },
        {
            "venue": "Paselino Sportsbar",
            "street": "Daimlerstraße 2",
            "city": "Wiernsheim",
            "phone": "",
            "fax": "",
            "contact": "Marcel Reiling",
            "mobile": "0170 7121050",
            "website": "http://www.paselino.de",
            "contact_email": "dartanions@web.de",
            "email": "info@paselino.de",
            "name": "DC DARTanions",
            "number": "068",
            "url": "https://www.bwedl.de/vereine/dc-dartanions/"
        },
        {
            "venue": "TSV Grunbach",
            "street": "Eichbergstr. 75",
            "city": "Engelsbrand-Grunbach",
            "phone": "",
            "fax": "",
            "contact": "Sven Thomas",
            "mobile": "0176 61269209",
            "website": "http://www.tsv-grunbach.com",
            "contact_email": "info@tl-thomas.com",
            "email": "info@tl-thomas.com",
            "name": "TSV Grunbach Darts",
            "number": "069",
            "url": "https://www.bwedl.de/vereine/tsv-grunbach-darts/"
        },
        {
            "venue": "ESV Pforzheim 1929 e.V.",
            "street": "Emil-Keßler-Str. 15",
            "city": "Pforzheim",
            "phone": "",
            "fax": "",
            "contact": "Wolfgang Loss",
            "mobile": "01520 6205376",
            "website": "",
            "contact_email": "wgloss@web.de",
            "email": "hansiliza_1884@yahoo.de",
            "name": "ESV DC 25",
            "number": "070",
            "url": "https://www.bwedl.de/vereine/esv-dc-25/"
        },
        {
            "venue": "Schindelstüble",
            "street": "Rennbachstrasse 17",
            "city": "Bad Wildbad",
            "phone": "01523 8521609",
            "fax": "",
            "contact": "Corinna Diether",
            "mobile": "0152 39532764",
            "website": "",
            "contact_email": "corinna255@web.de",
            "email": "",
            "name": "The Walking Darts",
            "number": "071",
            "url": "https://www.bwedl.de/vereine/the-walking-darts/"
        },
        {
            "venue": "The Dubliner Irish Pub",
            "street": "Hauptstr. 105",
            "city": "Straubenhardt",
            "phone": "",
            "fax": "",
            "contact": "Marvin Paar",
            "mobile": "0151 51706837",
            "website": "",
            "contact_email": "marvin-paar@gmx.de",
            "email": "dirk.schuhmacher@gmx.net",
            "name": "DC Hot Shotz",
            "number": "072",
            "url": "https://www.bwedl.de/vereine/dc-hot-shotz/"
        },
        {
            "venue": "Meyerhöfle",
            "street": "Bertholdstr. 28",
            "city": "Pforzheim",
            "phone": "07231 5899406",
            "fax": "",
            "contact": "Melanie Robertus-Dondalski",
            "mobile": "0176 63352002",
            "website": "",
            "contact_email": "melanie.robertus@gmx.de",
            "email": "",
            "name": "DC Höfle",
            "number": "075",
            "url": "https://www.bwedl.de/vereine/dc-hofle/"
        },
        {
            "venue": "X Cafe",
            "street": "Westliche-Karl-Friedrich-Str. 261",
            "city": "Pforzheim",
            "phone": "0157 30854547",
            "fax": "",
            "contact": "Mario Ackermann",
            "mobile": "0176 45984718",
            "website": "",
            "contact_email": "bomer2003@t-online.de",
            "email": "beti.luca@yahoo.de",
            "name": "Heavy Weigths Brötzingen",
            "number": "076",
            "url": "https://www.bwedl.de/vereine/076-heavy-weigths-brotzingen/"
        },
        {
            "venue": "Pharao Niefern",
            "street": "",
            "city": "Niefern-Öschelbronn",
            "phone": "0176 61966811",
            "fax": "",
            "contact": "Eros Schembri",
            "mobile": "0176 78638739",
            "website": "",
            "contact_email": "schembri.eros@web.de",
            "email": "",
            "name": "United Ikaros",
            "number": "077",
            "url": "https://www.bwedl.de/vereine/united-ikaros/"
        },
        {
            "venue": "Art Cafe",
            "street": "Wilhelmstraße 36",
            "city": "Bad Wildbad",
            "phone": "",
            "fax": "",
            "contact": "Sanel Bozic",
            "mobile": "0174 4859653",
            "website": "",
            "contact_email": "sanelboziccfc@gmail.com",
            "email": "",
            "name": "DC Williams",
            "number": "078",
            "url": "https://www.bwedl.de/vereine/dc-williams/"
        }
    ]
};